# Generated by Django 5.0.6 on 2024-10-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bookmodel_chatagentmodel_chatmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
