# Generated by Django 5.0.6 on 2024-10-30 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_langchainpgcollection_langchainpgembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 30, 12, 10, 27, 11907, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
