# Generated by Django 5.0.6 on 2024-11-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bookmodel_created_at_bookmodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
