# Generated by Django 5.0.6 on 2024-11-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usermodel_thread_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='thread_id',
            field=models.CharField(max_length=255),
        ),
    ]
