# Generated by Django 5.0.6 on 2024-11-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_usermodel_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='file_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
